active_profiles = []

[shell.fish]
use_abbr = true

[aliases]
comcomp = "{{1}} completion fish > /Users/winnie/.local/share/chezmoi/private_dot_config/fish/completions/{{1}}.fish"
comcomps = "{{1}} completions fish > /Users/winnie/.local/share/chezmoi/private_dot_config/fish/completions/{{1}}.fish"
ddb = "duckdb --cmd '.read ~/dev/02_spellbook/pastel_duck_theme.sql'"
gri = "git rebase -i --autosquash HEAD~{{1}}"
ltd = "lsd --tree --depth={{1}}"
ssx = "ssh -A {{1}}.exe.xyz"
