[global]
# standard markdownlint disabled rules
# MD057 is uniqe to this repo because chezmoi dotfiles
# are not always in the normal target relationship to each other
# so relative links look broken but are correct in the target directory
disable = ["line-length", "no-duplicate-heading", "first-line-h1", "no-inline-html", "MD057"]
exclude = [
  "./.chezmoitemplates/agents/AGENTS.md,",
  "skills/developing-in-lightdash",
]
flavor = "github"
