protocol file
mime image/*
action launch --type=overlay kitten icat --hold -- ${FILE_PATH}

protocol file
fragment_matches [0-9]+
action launch --type=tab --cwd=current -- mise exec -- ${EDITOR} +${FRAGMENT} -- ${FILE_PATH}

protocol file
mime text/*
action launch --type=tab --cwd=current -- mise exec -- ${EDITOR} -- ${FILE_PATH}
