[aliases]
brsf = "brew search {{1}} | fzf --multi --prompt='Filter results: ' --preview='brew info {1}'"
ccp = "cat {{1}} | fish_clipboard_copy"
clm = "claude --model {{1}} --effort {{2}}"
cxsol = """codex -m gpt-5.6-sol -c 'model_reasoning_effort="{{1}}"'"""
gcliff = 'git cliff --unreleased --tag "{{1}}" --strip all'
ghscr = 'gh search code "{{1}} repo:{{2}}"'
ghsld = 'gh search code "{{1}} repo:lightdash/lightdash"'
ghsldw = 'gh search code --web "{{1}} repo:lightdash/lightdash"'
gri = "git rebase -i --autosquash HEAD~{{1}}"
helpr = "{{1}} --help | bat -plhelp | rg {{2}}"
ltd = "lsd --tree --depth={{1}}"
pport = "lsof -i :{{1}}"
zipr = "zip -r {{1}}.zip {{1}}/"

[shell]

[logging]
project_loading = "off"
project_unloading = "off"

[update]
check = false
