[aliases]
brsf = "brew search {{1}} | fzf --multi --prompt='Filter results: ' --preview='brew info {1}'"
ccp = "cat {{1}} | fish_clipboard_copy"
ddb = "duckdb --cmd '.read ~/dev/02_spellbook/pastel_duck_theme.sql'"
gcliff = 'git cliff --unreleased --tag "{{1}}" --strip all'
ghscr = 'gh search code "{{1}} repo:{{2}}"'
ghsld = 'gh search code "{{1}} repo:lightdash/lightdash"'
ghsldw = 'gh search code --web "{{1}} repo:lightdash/lightdash"'
gri = "git rebase -i --autosquash HEAD~{{1}}"
hlpr = "{{1}} --help | bat -plhelp | rg {{2}}"
ltd = "lsd --tree --depth={{1}}"
pport = "lsof -i :{{1}}"
ski = "aubx skills@latest"
skia = "ski add {{1}}"
skiag = "ski add -g {{1}}"
skih = "aubx skills --help"
skils = "aubx skills list -g"
skirm = "aubx skills remove"
skis = "ski search {{1}}"
skiup = "aubx skills update"
spc = "sprite console -s {{1}}"
spd = "sprite destroy"
spls = "sprite list"
spx = "sprite exec -s {{1}} {{2}}"
ssx = "ssh -A {{1}}.exe.xyz"
uvlt = "uv pip tree --depth {{1}}"

[shell]

[logging]
project_loading = "off"
project_unloading = "off"

[update]
check = false
