[[profiles]]
name = "aube"

[profiles.aliases]
tsb = "aube build"
tsch = "aube check"
tsd = "aube dev"
tsf = "aube format"
tsl = "aube lint"
tsp = "aube preview"
tss = "aube start"
tst = "aube test"
tstc = "aube typecheck"

[[profiles]]
name = "bun"

[profiles.aliases]
tsb = "bun build"
tsch = "bun check"
tsd = "bun dev"
tsf = "bun format"
tsl = "bun lint"
tsp = "bun preview"
tss = "bun start"
tst = "bun test"
tstc = "bun typecheck"

[[profiles]]
name = "deno"

[profiles.aliases]
tsb = "deno task build"
tsch = "deno task check"
tsd = "deno task dev"
tsf = "deno fmt"
tsl = "deno lint"
tsp = "deno task preview"
tss = "deno task start"
tst = "deno test"
tstc = "deno check"

[[profiles]]
name = "npm"

[profiles.aliases]
tsb = "npm run build"
tsch = "npm run check"
tsd = "npm run dev"
tsf = "npm run format"
tsl = "npm run lint"
tsp = "npm run preview"
tss = "npm start"
tst = "npm test"
tstc = "npm run typecheck"

[[profiles]]
name = "pnpm"

[profiles.aliases]
tsb = "pnpm build"
tsch = "pnpm check"
tsd = "pnpm dev"
tsf = "pnpm format"
tsl = "pnpm lint"
tsp = "pnpm preview"
tss = "pnpm start"
tst = "pnpm test"
tstc = "pnpm typecheck"
