function __git_wash_needs_repo
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 2
    and contains -- $tokens[2] list wash snapshot
end

function __git_wash_needs_target
    set -l tokens (commandline -opc)
    test (count $tokens) -eq 3
    and test "$tokens[2]" = wash
end

complete -c git-wash -f
complete -c git-wash -n "not __fish_seen_subcommand_from list wash snapshot" -a list -d "Generate tier reports and an agent review file"
complete -c git-wash -n "not __fish_seen_subcommand_from list wash snapshot" -a snapshot -d "Back up every remote branch to a verified bundle"
complete -c git-wash -n "not __fish_seen_subcommand_from list wash snapshot" -a wash -d "Preview or delete a manifest target"
complete -c git-wash -s h -l help -d "Show help"
complete -c git-wash -s V -l version -d "Show version"

complete -c git-wash -n __git_wash_needs_repo -F
complete -c git-wash -n __git_wash_needs_target -a tier1 -d "Ancestry-merged or exact merged-PR tips"
complete -c git-wash -n __git_wash_needs_target -a tier2 -d "Patch-equivalent commits on the default branch"
complete -c git-wash -n __git_wash_needs_target -a tier3 -d "Unproven stale branches requiring exceptional intent"
complete -c git-wash -n __git_wash_needs_target -a reviewed -d "Agent-reviewed Tier 3 deletion recommendations"
complete -c git-wash -n __git_wash_needs_target -a test -d "Up to ten of the oldest Tier 1 branches"

complete -c git-wash -n "__fish_seen_subcommand_from list" -s o -l output -d "Artifact output directory" -r -F
complete -c git-wash -n "__fish_seen_subcommand_from list snapshot" -l remote -d "Git remote to inspect" -r -f -a "(git remote 2>/dev/null)"
complete -c git-wash -n "__fish_seen_subcommand_from list" -l github-repo -d "Explicit [host/]owner/repo for GitHub metadata" -r -f
complete -c git-wash -n "__fish_seen_subcommand_from list" -l stale-days -d "Minimum tip commit age" -r -f
complete -c git-wash -n "__fish_seen_subcommand_from list" -l skip-fetch -d "Use existing remote-tracking refs"

complete -c git-wash -n "__fish_seen_subcommand_from snapshot" -s o -l output -d "Bundle output directory" -r -F

complete -c git-wash -n "__fish_seen_subcommand_from wash" -s m -l manifest -d "Manifest generated by list" -r -F
complete -c git-wash -n "__fish_seen_subcommand_from wash" -s r -l reviews -d "Agent review decisions" -r -F
complete -c git-wash -n "__fish_seen_subcommand_from wash" -l execute -d "Delete SHA-matched remote branches"
