#!/usr/bin/env fish
# fish completion support for rei vv0.1.0 (source ~/.config/reishi/skills)

function __fish_rei_using_command
  set -l cmds __rei __rei_skills __rei_skills_new __rei_skills_validate __rei_skills_add __rei_skills_list __rei_skills_activate __rei_skills_deactivate __rei_skills_sync __rei_skills_pull __rei_config __rei_config_init __rei_config_show __rei_config_path __rei_sync __rei_rules __rei_rules_list __rei_rules_sync __rei_docs __rei_docs_list __rei_docs_add __rei_docs_remove __rei_docs_sync __rei_completions __rei_completions_bash __rei_completions_fish __rei_completions_zsh
  set -l words (commandline -opc)
  set -l cmd "_"
  for word in $words
    switch $word
      case '-*'
        continue
      case '*'
        set word (string replace -r -a '\W' '_' $word)
        set -l cmd_tmp $cmd"_$word"
        if contains $cmd_tmp $cmds
          set cmd $cmd_tmp
        end
    end
  end
  if test "$cmd" = "$argv[1]"
    return 0
  end
  return 1
end

complete -c rei -n '__fish_rei_using_command __rei' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei' -s V -l version -x -k -f -d 'Show the version number for this program.'
complete -c rei -n '__fish_rei_using_command __rei' -k -f -a skills -d 'Manage conditionally-activated agent context (skills)'
complete -c rei -n '__fish_rei_using_command __rei_skills' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a new -d 'Scaffold a new skill from the embedded template'
complete -c rei -n '__fish_rei_using_command __rei_skills_new' -k -f -a '(rei completions complete string skills new)'
complete -c rei -n '__fish_rei_using_command __rei_skills_new' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills_new' -s p -l path -k -f -r -a '(rei completions complete string skills new)' -d 'Base path for new skill (defaults to config source)'
complete -c rei -n '__fish_rei_using_command __rei_skills_new' -s f -l fork -k -f -r -a '(rei completions complete string skills new)' -d 'Use a GitHub repo as the skill basis (main branch HEAD)'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a validate -d 'Validate skill structure and frontmatter'
complete -c rei -n '__fish_rei_using_command __rei_skills_validate' -k -f -a '(rei completions complete string skills validate)'
complete -c rei -n '__fish_rei_using_command __rei_skills_validate' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a add -d 'Add skill(s) from a GitHub tree URL — single skill or a whole skills directory'
complete -c rei -n '__fish_rei_using_command __rei_skills_add' -k -f -a '(rei completions complete string skills add)'
complete -c rei -n '__fish_rei_using_command __rei_skills_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills_add' -l path -k -f -r -a '(rei completions complete string skills add)' -d 'Destination directory for added skills (defaults to config source)'
complete -c rei -n '__fish_rei_using_command __rei_skills_add' -s t -l track -k -f -d 'Record skill origin in the lockfile for later pulls'
complete -c rei -n '__fish_rei_using_command __rei_skills_add' -s p -l prefix -k -f -r -a '(rei completions complete string skills add)' -d 'Prefix skill names with an org/user (no value = infer from URL)'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a list -d 'List skills'
complete -c rei -n '__fish_rei_using_command __rei_skills_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills_list' -s a -l all -k -f -d 'Include deactivated skills'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a activate -d 'Move a skill from deactivated to active'
complete -c rei -n '__fish_rei_using_command __rei_skills_activate' -k -f -a '(rei completions complete deactivated-skill skills activate)'
complete -c rei -n '__fish_rei_using_command __rei_skills_activate' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a deactivate -d 'Move a skill from active to deactivated'
complete -c rei -n '__fish_rei_using_command __rei_skills_deactivate' -k -f -a '(rei completions complete active-skill skills deactivate)'
complete -c rei -n '__fish_rei_using_command __rei_skills_deactivate' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a sync -d 'Distribute skills from source to configured targets (local only)'
complete -c rei -n '__fish_rei_using_command __rei_skills_sync' -k -f -a '(rei completions complete active-skill skills sync)'
complete -c rei -n '__fish_rei_using_command __rei_skills_sync' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills_sync' -l agents -k -f -r -a '(rei completions complete string skills sync)' -d 'Comma-separated agent names to sync to'
complete -c rei -n '__fish_rei_using_command __rei_skills_sync' -l method -k -f -r -a '(rei completions complete string skills sync)' -d 'Override sync method: copy or symlink'
complete -c rei -n '__fish_rei_using_command __rei_skills_sync' -l dry-run -k -f -d 'Plan only — do not write'
complete -c rei -n '__fish_rei_using_command __rei_skills_sync' -l check -k -f -d 'Report per skill × target freshness without writing'
complete -c rei -n '__fish_rei_using_command __rei_skills' -k -f -a pull -d 'Fetch upstream for tracked skills, then auto-sync to targets'
complete -c rei -n '__fish_rei_using_command __rei_skills_pull' -k -f -a '(rei completions complete active-skill skills pull)'
complete -c rei -n '__fish_rei_using_command __rei_skills_pull' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_skills_pull' -l agents -k -f -r -a '(rei completions complete string skills pull)' -d 'Comma-separated agent names to sync to'
complete -c rei -n '__fish_rei_using_command __rei_skills_pull' -l method -k -f -r -a '(rei completions complete string skills pull)' -d 'Override sync method: copy or symlink'
complete -c rei -n '__fish_rei_using_command __rei_skills_pull' -l dry-run -k -f -d 'Preview upstream diff without writing (no sync either)'
complete -c rei -n '__fish_rei_using_command __rei_skills_pull' -l check -k -f -d 'Check for upstream changes without fetching'
complete -c rei -n '__fish_rei_using_command __rei_skills_pull' -l prefix-change -k -f -r -a '(rei completions complete string skills pull)' -d 'How to handle a changed prefix non-interactively: rename | parallel | abort'
complete -c rei -n '__fish_rei_using_command __rei' -k -f -a config -d 'Inspect and manage reishi config'
complete -c rei -n '__fish_rei_using_command __rei_config' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_config' -k -f -a init -d 'Create the reishi config file and source directories'
complete -c rei -n '__fish_rei_using_command __rei_config_init' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_config' -k -f -a show -d 'Print the effective config (merged with defaults)'
complete -c rei -n '__fish_rei_using_command __rei_config_show' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_config' -k -f -a path -d 'Print the config file path'
complete -c rei -n '__fish_rei_using_command __rei_config_path' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei' -k -f -a sync -d 'Sync skills, rules, and docs from source to targets (local only)'
complete -c rei -n '__fish_rei_using_command __rei_sync' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_sync' -l agents -k -f -r -a '(rei completions complete string sync)' -d 'Comma-separated agent names to sync to'
complete -c rei -n '__fish_rei_using_command __rei_sync' -l method -k -f -r -a '(rei completions complete string sync)' -d 'Override sync method: copy or symlink'
complete -c rei -n '__fish_rei_using_command __rei_sync' -l dry-run -k -f -d 'Plan only — do not write'
complete -c rei -n '__fish_rei_using_command __rei' -k -f -a rules -d 'Manage always-on markdown rules distributed to agent rule paths'
complete -c rei -n '__fish_rei_using_command __rei_rules' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_rules' -k -f -a list -d 'List rules in rules.source'
complete -c rei -n '__fish_rei_using_command __rei_rules_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_rules' -k -f -a sync -d 'Sync rules from source to configured agent targets'
complete -c rei -n '__fish_rei_using_command __rei_rules_sync' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_rules_sync' -l agents -k -f -r -a '(rei completions complete string rules sync)' -d 'Comma-separated agent names to sync to'
complete -c rei -n '__fish_rei_using_command __rei_rules_sync' -l method -k -f -r -a '(rei completions complete string rules sync)' -d 'Override sync method: copy or symlink'
complete -c rei -n '__fish_rei_using_command __rei_rules_sync' -l dry-run -k -f -d 'Plan only — do not write'
complete -c rei -n '__fish_rei_using_command __rei' -k -f -a docs -d 'Manage project-scoped doc fragments compiled into a token-efficient index'
complete -c rei -n '__fish_rei_using_command __rei_docs' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_docs' -k -f -a list -d 'List doc projects, or fragments within a project'
complete -c rei -n '__fish_rei_using_command __rei_docs_list' -k -f -a '(rei completions complete doc-project docs list)'
complete -c rei -n '__fish_rei_using_command __rei_docs_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_docs' -k -f -a add -d 'Create a doc project: makes the source dir and config entry'
complete -c rei -n '__fish_rei_using_command __rei_docs_add' -k -f -a '(rei completions complete string docs add)'
complete -c rei -n '__fish_rei_using_command __rei_docs_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_docs_add' -l target -k -f -r -a '(rei completions complete string docs add)' -d 'Project root on disk for sync'
complete -c rei -n '__fish_rei_using_command __rei_docs_add' -l force -k -f -d 'Re-use an existing source dir instead of erroring'
complete -c rei -n '__fish_rei_using_command __rei_docs' -k -f -a remove -d 'Remove a doc project — two-step: config entry, then optionally source dir'
complete -c rei -n '__fish_rei_using_command __rei_docs_remove' -k -f -a '(rei completions complete doc-project docs remove)'
complete -c rei -n '__fish_rei_using_command __rei_docs_remove' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_docs_remove' -l force -k -f -d 'Skip the config-entry confirmation prompt'
complete -c rei -n '__fish_rei_using_command __rei_docs_remove' -l delete-source -k -f -d 'Also delete the source dir (default: keep it)'
complete -c rei -n '__fish_rei_using_command __rei_docs' -k -f -a sync -d 'Compile and distribute docs for one or all configured projects'
complete -c rei -n '__fish_rei_using_command __rei_docs_sync' -k -f -a '(rei completions complete doc-project docs sync)'
complete -c rei -n '__fish_rei_using_command __rei_docs_sync' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_docs_sync' -l target -k -f -r -a '(rei completions complete string docs sync)' -d 'Override the target project root (requires <project>)'
complete -c rei -n '__fish_rei_using_command __rei_docs_sync' -l method -k -f -r -a '(rei completions complete string docs sync)' -d 'Override sync method: copy or symlink'
complete -c rei -n '__fish_rei_using_command __rei_docs_sync' -l dry-run -k -f -d 'Plan only — do not write'
complete -c rei -n '__fish_rei_using_command __rei_docs_sync' -l stdout -k -f -d 'Emit the compiled index to stdout (requires <project>)'
complete -c rei -n '__fish_rei_using_command __rei' -k -f -a completions -d 'Generate shell completions.'
complete -c rei -n '__fish_rei_using_command __rei_completions' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_completions' -k -f -a bash -d 'Generate shell completions for bash.'
complete -c rei -n '__fish_rei_using_command __rei_completions_bash' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_completions_bash' -s n -l name -k -f -r -a '(rei completions complete string completions bash)' -d 'The name of the main command.'
complete -c rei -n '__fish_rei_using_command __rei_completions' -k -f -a fish -d 'Generate shell completions for fish.'
complete -c rei -n '__fish_rei_using_command __rei_completions_fish' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_completions_fish' -s n -l name -k -f -r -a '(rei completions complete string completions fish)' -d 'The name of the main command.'
complete -c rei -n '__fish_rei_using_command __rei_completions' -k -f -a zsh -d 'Generate shell completions for zsh.'
complete -c rei -n '__fish_rei_using_command __rei_completions_zsh' -s h -l help -x -k -f -d 'Show this help.'
complete -c rei -n '__fish_rei_using_command __rei_completions_zsh' -s n -l name -k -f -r -a '(rei completions complete string completions zsh)' -d 'The name of the main command.'
