complete -c spx -s o -l org -x -d "Specify organization"
complete -c spx -s s -l sprite -x -a "(_sprite_names)" -d "Specify sprite"
complete -c spx -l dir -r -d "Set working directory"
complete -c spx -l tty -d "Allocate pseudo-TTY"
complete -c spx -l env -x -d "Set environment variables"
complete -c spx -l http-post -d "Use HTTP/1.1 POST"
complete -c spx -l no-port-forward -d "Disable automatic local port forwarding"
complete -c spx -l file -r -d "Upload source:destination before exec"
complete -c spx -s h -l help -d "Show help"
