[tools]
node = ["lts", "latest"]
aube = "latest"

"npm:@agentclientprotocol/claude-agent-acp" = "latest"
"npm:@aredotna/cli" = "latest"
"npm:@opencode-ai/cli" = [{ version = "beta", allow_builds = ["@opencode-ai/cli"] }]
"npm:@readwise/cli" = "latest"
"npm:mint" = "latest"
"npm:portless" = "latest"
"npm:sfw" = "latest"
"npm:supabase" = "latest"
"npm:@zvec/zvec-grep" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age_excludes = ["aube"]
