[tools]
node = ["lts", "latest"]
aube = "latest"

"npm:@agentclientprotocol/claude-agent-acp" = "latest"
"npm:@aredotna/cli" = "latest"
"npm:@readwise/cli" = "latest"
"npm:supabase" = "latest"
"npm:sfw" = "latest"
"npm:mint" = "latest"
"npm:portless" = "latest"
"npm:@opencode-ai/cli" = { version = "next", allow_builds = ["@opencode-ai/cli"] }

[settings]
npm.package_manager = "aube"
idiomatic_version_file_enable_tools = ["node"]
