[tools]
node = ["lts", "latest"]

"npm:@agentclientprotocol/claude-agent-acp" = "latest"
"npm:@aredotna/cli" = "latest"
"npm:@readwise/cli" = "latest"
"npm:mint" = "latest"
"npm:portless" = "latest"
"npm:supabase" = "latest"

[settings]
npm.package_manager = "pnpm"
idiomatic_version_file_enable_tools = ["node"]
