[tool_alias]
# temporary until next mise release which fixes
# attestation resolution for transferred gh repos
aube = "github:aubepkg/aube"

[tools]
node = ["lts", "latest"]

"npm:@agentclientprotocol/claude-agent-acp" = "latest"
"npm:@aredotna/cli" = "latest"
"npm:@opencode-ai/cli" = [{ version = "beta", allow_builds = ["@opencode-ai/cli"] }]
"npm:@readwise/cli" = "latest"
"npm:mint" = "latest"
"npm:portless" = "latest"
"npm:sfw" = "latest"
"npm:supabase" = "latest"

[tools.aube]
version = "2.2.12"
# minimum_release_age = "2d"

[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age_excludes = ["aube"]
